services:
  postgres:
    image: postgres:16
    container_name: ChatApp_discussion
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mdp
      POSTGRES_DB: discussion
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5433"
    volumes:
      - ./data/postgre:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: